### ISSUE TITLE
Заполнение.

### ISSUE THREAD

**Issue by MegaDen58** [MegaDen58/MegaDenFeatDima#4]
Заполнить все элементы списка информацией.

**Comment by MegaDen58** [comment]
Оформлены 2 темы: "Первый годы" и  "Пик популярности". Над "Началом популярности" работает Дмитрий. Дальше - больше! P.S. Темы можно листать.
![iIlplRcsKY8](https://user-images.githubusercontent.com/96517069/163727072-d201180b-204d-4e92-afba-463552fee5b3.jpg)
![c4kxGAKRang](https://user-images.githubusercontent.com/96517069/163727073-a56f84ba-d5fc-4da5-a5b8-b3db7a9e3f75.jpg)
![UeucMCxpHnA](https://user-images.githubusercontent.com/96517069/163727075-e22036c4-3e6b-4e3f-9d94-7789635423d8.jpg)
![I8vLOLX8bkA](https://user-images.githubusercontent.com/96517069/163727076-c7bee086-63da-4f34-8c36-1ede887b2864.jpg)

**Comment by MegaDen58** [comment]
Заполнен активити под названием "Смена состава"
![iwM2tyfsF1c](https://user-images.githubusercontent.com/96517069/163727849-58f3cd8c-e2df-4bce-b2dd-b87fba77849b.jpg)
![lt9Udmvn_gA](https://user-images.githubusercontent.com/96517069/163727850-d84f20b4-394a-4dd0-aaa2-f993d186d56b.jpg)

**Comment by MegaDen58** [comment]
Заполнены активити под названиями "Уход Князева. Возвращение Ренегата" и "Смерть Михаила Горшенёва и распад группы"
![yeUUa72OCRE](https://user-images.githubusercontent.com/96517069/163728870-21be25bc-eb05-499a-a69c-da330f07d89e.jpg)
![saZKMQzgL3M](https://user-images.githubusercontent.com/96517069/163728871-4ca21237-5779-41ae-b4b9-db7bb7a4f558.jpg)
![2ohefd9onUg](https://user-images.githubusercontent.com/96517069/163728872-a5d3eec4-8383-4440-b9b7-927eaf3773cf.jpg)
![V7RAp0nSoj0](https://user-images.githubusercontent.com/96517069/163728873-1141016b-8915-49a2-af0e-eb23e57330c1.jpg)

**Comment by artokit** [comment]
Молодец, но твой напарник сделал побольше. Старайся !

**Comment by artokit** [comment]
![image](https://user-images.githubusercontent.com/66463902/166558544-0ce306be-6f53-40ad-8d1a-a6a30ab98b54.png)

**Comment by MegaDen58** [comment]
Все молодцы!
